title: Luise Kollars
description:
  en: Artist
  de: KÃ¼nstlerin
permalink: pretty
baseurl: "https://luisekollars.github.io"
email: luise.kollars@gmail.com
gems:
  - jekyll-sitemap
exclude: ["node_modules",
  "assets/css/0-tools",
  "assets/css/1-base",
  "assets/css/2-modules",
  "assets/css/3-layout",
  "assets/css/fonts",
  "assets/css/*.scss",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md",
  "LICENSE.md"]
